#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# File: scripts/reporting/sasd-run-readonly-checks.sh
# Purpose: Run a curated set of read-only SASD Linux admin checks and collect
#          their output into one timestamped report directory.
# Project: admin-toolkit-linux
# License: MIT
# -----------------------------------------------------------------------------
# Safety model
# ------------
# This script is intentionally a collector, not a repair tool. It only calls
# read-only scripts from this repository and stores their stdout/stderr in files.
# It does not change system configuration, stop/start services, install packages,
# remove files, or modify permissions.
#
# Why this script exists
# ----------------------
# A toolbox with many small scripts is useful, but operational work often needs a
# repeatable "run the safe checks and give me a folder with results" entry point.
# This wrapper makes that possible while keeping the individual scripts readable
# and independently usable.
#
# Notes
# -----
# - Some child scripts use non-zero exit codes when they find something worth
#   reviewing. That does not necessarily mean the collector failed.
# - Reports can contain hostnames, usernames, IP addresses, package names and
#   local paths. Review the output before sharing it publicly.
# -----------------------------------------------------------------------------

set -u
set -o pipefail

SCRIPT_NAME="$(basename "$0")"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
HOSTNAME_SHORT="$(hostname -s 2>/dev/null || hostname 2>/dev/null || echo unknown-host)"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
DEFAULT_OUTPUT="$REPO_ROOT/reports/${HOSTNAME_SHORT}-${TIMESTAMP}"
OUTPUT_DIR="$DEFAULT_OUTPUT"
TIMEOUT_SECONDS="120"
INCLUDE_SLOW="no"

show_help() {
    cat <<HELP
Usage: $SCRIPT_NAME [OPTIONS]

Run selected read-only admin checks and collect their output.

Options:
  --output DIR        Write report files to DIR.
                      Default: reports/<host>-<timestamp>
  --timeout SECONDS   Per-command timeout when the timeout(1) command exists.
                      Default: 120
  --include-slow      Also run slower checks that may walk larger directory trees.
  -h, --help          Show this help text.

Examples:
  ./$SCRIPT_NAME
  ./$SCRIPT_NAME --output /tmp/sasd-report-dev102
  ./$SCRIPT_NAME --include-slow --output ./reports/full-check

Exit codes:
  0  Collector finished. Review INDEX.md for individual command statuses.
  2  Invalid command-line arguments or output directory problem.
HELP
}

fail() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 2
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)
            [[ $# -ge 2 ]] || fail "--output requires a directory argument"
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --timeout)
            [[ $# -ge 2 ]] || fail "--timeout requires a numeric argument"
            [[ "$2" =~ ^[0-9]+$ ]] || fail "--timeout must be numeric"
            TIMEOUT_SECONDS="$2"
            shift 2
            ;;
        --include-slow)
            INCLUDE_SLOW="yes"
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            fail "unknown option: $1"
            ;;
    esac
done

mkdir -p "$OUTPUT_DIR" || fail "cannot create output directory: $OUTPUT_DIR"

INDEX_FILE="$OUTPUT_DIR/INDEX.md"
STATUS_FILE="$OUTPUT_DIR/status.tsv"

cat > "$INDEX_FILE" <<HEADER
# SASD Read-only Check Collection

- Generated: $(date -Is)
- Host: ${HOSTNAME_SHORT}
- Repository root: \`${REPO_ROOT}\`
- Output directory: \`${OUTPUT_DIR}\`

> This collection was generated by read-only toolkit scripts. Review all output
> before sharing it publicly because reports can contain environment details.

## Command status

| Status | Script | Output |
| ---: | --- | --- |
HEADER

printf 'status\tscript\toutput\n' > "$STATUS_FILE"

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

run_script() {
    local relative_script="$1"
    local output_name="$2"
    local script_path="$REPO_ROOT/$relative_script"
    local output_path="$OUTPUT_DIR/$output_name"
    local status=0

    if [[ ! -x "$script_path" ]]; then
        printf 'SKIP: %s is not executable or not present\n' "$relative_script" > "$output_path"
        printf '| SKIP | `%s` | [`%s`](%s) |\n' "$relative_script" "$output_name" "$output_name" >> "$INDEX_FILE"
        printf 'SKIP\t%s\t%s\n' "$relative_script" "$output_name" >> "$STATUS_FILE"
        return 0
    fi

    {
        printf '# %s\n\n' "$relative_script"
        printf 'Generated: %s\n' "$(date -Is)"
        printf 'Command: %s\n\n' "$script_path"
        printf -- '--- output begins ---\n\n'
    } > "$output_path"

    if command_exists timeout; then
        timeout "$TIMEOUT_SECONDS" "$script_path" >> "$output_path" 2>&1
        status=$?
    else
        "$script_path" >> "$output_path" 2>&1
        status=$?
    fi

    {
        printf '\n--- output ends ---\n'
        printf 'Exit status: %s\n' "$status"
    } >> "$output_path"

    printf '| %s | `%s` | [`%s`](%s) |\n' "$status" "$relative_script" "$output_name" "$output_name" >> "$INDEX_FILE"
    printf '%s\t%s\t%s\n' "$status" "$relative_script" "$output_name" >> "$STATUS_FILE"
}

# Host documentation.
run_script "scripts/host-doc/sasd-host-inventory.sh" "01-host-inventory.md"
run_script "scripts/host-doc/sasd-service-inventory.sh" "02-service-inventory.md"
run_script "scripts/host-doc/sasd-package-inventory.sh" "03-package-inventory.md"

# Filesystem and process/file-handle review.
run_script "scripts/filesystem/sasd-disk-usage-report.sh" "10-disk-usage.md"
run_script "scripts/filesystem/sasd-deleted-open-files.sh" "11-deleted-open-files.md"

# Configuration review.
run_script "scripts/config/sasd-sshd-config-report.sh" "20-sshd-config.md"
run_script "scripts/config/sasd-sudoers-report.sh" "21-sudoers.md"
run_script "scripts/config/sasd-journald-config-report.sh" "22-journald-config.md"
run_script "scripts/config/sasd-logrotate-report.sh" "23-logrotate.md"

# Security and account review.
run_script "scripts/security/sasd-open-ports-audit.sh" "30-open-ports.md"
run_script "scripts/network/sasd-listening-services-report.sh" "31-listening-services.md"
run_script "scripts/security/sasd-ssh-baseline-check.sh" "32-ssh-baseline.md"
run_script "scripts/security/sasd-system-accounts-audit.sh" "33-system-accounts.md"
run_script "scripts/accounts/sasd-account-baseline.sh" "34-account-baseline.tsv"
run_script "scripts/security/sasd-suid-sgid-audit.sh" "35-suid-sgid.md"
run_script "scripts/security/sasd-world-writable-audit.sh" "36-world-writable.md"
run_script "scripts/security/sasd-sensitive-files-check.sh" "37-sensitive-files.md"

# Logging and package/reboot state.
run_script "scripts/logging/sasd-journal-errors.sh" "40-journal-errors.md"
run_script "scripts/logging/sasd-auth-log-report.sh" "41-auth-log.md"
run_script "scripts/packages/sasd-update-status-report.sh" "50-update-status.md"
run_script "scripts/packages/sasd-reboot-required-report.sh" "51-reboot-required.md"

# Summary reports call other scripts and can be longer, but they are useful as a
# human-readable top-level view.
run_script "scripts/reporting/sasd-admin-summary.sh" "90-admin-summary.md"
run_script "scripts/reporting/sasd-security-summary.sh" "91-security-summary.md"

if [[ "$INCLUDE_SLOW" == "yes" ]]; then
    run_script "scripts/security/sasd-fim-baseline.sh" "95-fim-baseline.tsv"
fi

cat >> "$INDEX_FILE" <<FOOTER

## Notes

- Exit status 0 usually means OK or informational output.
- Exit status 1 can mean findings were detected by an audit script.
- Exit status 2 or higher usually means an execution problem or missing prerequisite.
- Review each report before sharing it outside your environment.
FOOTER

printf 'Report directory: %s\n' "$OUTPUT_DIR"
printf 'Index: %s\n' "$INDEX_FILE"
exit 0
