#!/usr/bin/env bash
#
# scripts/reporting/sasd-run-readonly-checks.sh
#
# Purpose:
#   Run the safe read-only checks in this repository and write a report
#   directory with an INDEX.md and status.tsv.
#
# Safety:
#   This wrapper only calls read-only scripts from the repository. It does not
#   repair findings and does not modify system configuration.

set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DEFAULT_OUTPUT="$REPO_ROOT/reports/$(hostname -s 2>/dev/null || echo host)-$(date +%Y%m%d-%H%M%S)"
OUTPUT_DIR="$DEFAULT_OUTPUT"
INCLUDE_SUMMARY=0

usage() {
  cat <<'USAGE'
Usage:
  sasd-run-readonly-checks.sh [options]

Options:
  --output DIR        Write reports to DIR. Default: reports/HOST-TIMESTAMP.
  --include-summary   Also run the large admin/security summary reports.
  -h, --help          Show help.

Examples:
  ./scripts/reporting/sasd-run-readonly-checks.sh
  ./scripts/reporting/sasd-run-readonly-checks.sh --output ./reports/dev102-test
  ./scripts/reporting/sasd-run-readonly-checks.sh --include-summary
USAGE
}

fail() { echo "ERROR: $*" >&2; exit 2; }

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --output)
        [[ $# -ge 2 ]] || fail "--output requires an argument"
        OUTPUT_DIR="$2"
        shift 2
        ;;
      --include-summary)
        INCLUDE_SUMMARY=1
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *) fail "unknown argument: $1" ;;
    esac
  done
}

run_report() {
  local rel_script="$1" output_name="$2" status_file="$3"
  local script_path="$REPO_ROOT/$rel_script"
  local output_path="$OUTPUT_DIR/$output_name"
  local status

  if [[ ! -x "$script_path" ]]; then
    printf '127\t%s\t%s\n' "$rel_script" "$output_name" >>"$status_file"
    {
      echo "# Missing script"
      echo
      echo "Script not executable or not found: $rel_script"
    } >"$output_path"
    return 0
  fi

  set +e
  "$script_path" >"$output_path" 2>&1
  status=$?
  set -e
  printf '%s\t%s\t%s\n' "$status" "$rel_script" "$output_name" >>"$status_file"
}

write_index() {
  local status_file="$1" index_file="$OUTPUT_DIR/INDEX.md"
  local generated host rel status script output

  generated="$(date --iso-8601=seconds)"
  host="$(hostname -s 2>/dev/null || hostname 2>/dev/null || echo unknown)"

  {
    printf '# SASD Read-only Check Collection\n\n'
    printf -- '- Generated: %s\n' "$generated"
    printf -- '- Host: %s\n' "$host"
    printf -- '- Repository root: `%s`\n' "$REPO_ROOT"
    printf -- '- Output directory: `%s`\n\n' "$OUTPUT_DIR"
    printf '> This collection was generated by read-only toolkit scripts. Review all output\n'
    printf '> before sharing it publicly because reports can contain environment details.\n\n'
    printf '## Command status\n\n'
    printf '| Status | Script | Output |\n'
    printf '| ---: | --- | --- |\n'
  } >"$index_file"

  tail -n +2 "$status_file" | while IFS=$'\t' read -r status script output; do
    [[ -n "${status:-}" ]] || continue
    printf '| %s | `%s` | [`%s`](%s) |\n' "$status" "$script" "$output" "$output" >>"$index_file"
  done

  cat >>"$index_file" <<'NOTES'

## Notes

- Exit status 0 usually means OK or informational output.
- Exit status 1 can mean findings were detected by an audit script.
- Exit status 2 or higher usually means an execution problem or missing prerequisite.
- Summary reports are excluded by default to avoid duplicated output. Use `--include-summary` when wanted.
- Symlink-aware permission reports evaluate target metadata where possible; symlink mode 777 alone is usually not a direct permission finding on Linux.
- Review each report before sharing it outside your environment.
NOTES
}

main() {
  parse_args "$@"
  mkdir -p "$OUTPUT_DIR"

  local status_file="$OUTPUT_DIR/status.tsv"
  printf 'status\tscript\toutput\n' >"$status_file"

  cd "$REPO_ROOT"

  run_report "scripts/host-doc/sasd-host-inventory.sh" "01-host-inventory.md" "$status_file"
  run_report "scripts/host-doc/sasd-service-inventory.sh" "02-service-inventory.md" "$status_file"
  run_report "scripts/host-doc/sasd-package-inventory.sh" "03-package-inventory.md" "$status_file"
  run_report "scripts/filesystem/sasd-disk-usage-report.sh" "10-disk-usage.md" "$status_file"
  run_report "scripts/filesystem/sasd-deleted-open-files.sh" "11-deleted-open-files.md" "$status_file"
  run_report "scripts/backup/sasd-backup-age-check.sh" "12-backup-age-check.md" "$status_file"

  run_report "scripts/config/sasd-sshd-config-report.sh" "20-sshd-config.md" "$status_file"
  run_report "scripts/config/sasd-sudoers-report.sh" "21-sudoers.md" "$status_file"
  run_report "scripts/config/sasd-journald-config-report.sh" "22-journald-config.md" "$status_file"
  run_report "scripts/config/sasd-logrotate-report.sh" "23-logrotate.md" "$status_file"
  run_report "scripts/config/sasd-cron-report.sh" "24-cron.md" "$status_file"
  run_report "scripts/config/sasd-systemd-timers-report.sh" "25-systemd-timers.md" "$status_file"
  run_report "scripts/config/sasd-browser-repo-report.sh" "26-browser-repos.md" "$status_file"

  run_report "scripts/security/sasd-open-ports-audit.sh" "30-open-ports.md" "$status_file"
  run_report "scripts/network/sasd-listening-services-report.sh" "31-listening-services.md" "$status_file"
  run_report "scripts/security/sasd-ssh-baseline-check.sh" "32-ssh-baseline.md" "$status_file"
  run_report "scripts/security/sasd-system-accounts-audit.sh" "33-system-accounts.md" "$status_file"
  run_report "scripts/accounts/sasd-account-baseline.sh" "34-account-baseline.tsv" "$status_file"
  run_report "scripts/security/sasd-suid-sgid-audit.sh" "35-suid-sgid.md" "$status_file"
  run_report "scripts/security/sasd-world-writable-audit.sh" "36-world-writable.md" "$status_file"
  run_report "scripts/security/sasd-sensitive-files-check.sh" "37-sensitive-files.md" "$status_file"
  run_report "scripts/security/sasd-permission-risk-report.sh" "38-permission-risk.md" "$status_file"
  run_report "scripts/security/sasd-root-owned-writable-report.sh" "39-root-owned-writable.md" "$status_file"
  run_report "scripts/security/sasd-symlink-target-report.sh" "40-symlink-targets.md" "$status_file"

  run_report "scripts/logging/sasd-journal-errors.sh" "41-journal-errors.md" "$status_file"
  run_report "scripts/logging/sasd-auth-log-report.sh" "42-auth-log.md" "$status_file"
  run_report "scripts/security/sasd-firewall-status-report.sh" "43-firewall-status.md" "$status_file"
  run_report "scripts/security/sasd-auditd-status-report.sh" "44-auditd-status.md" "$status_file"

  run_report "scripts/packages/sasd-update-status-report.sh" "50-update-status.md" "$status_file"
  run_report "scripts/packages/sasd-reboot-required-report.sh" "51-reboot-required.md" "$status_file"
  run_report "scripts/database/sasd-mariadb-inventory.sh" "80-mariadb-inventory.md" "$status_file"
  run_report "scripts/database/sasd-postgresql-inventory.sh" "81-postgresql-inventory.md" "$status_file"
  run_report "scripts/reporting/sasd-findings-summary.sh" "89-findings-summary.md" "$status_file"

  if [[ "$INCLUDE_SUMMARY" -eq 1 ]]; then
    run_report "scripts/reporting/sasd-admin-summary.sh" "90-admin-summary.md" "$status_file"
    run_report "scripts/reporting/sasd-security-summary.sh" "91-security-summary.md" "$status_file"
  fi

  write_index "$status_file"

  echo "Report directory: $OUTPUT_DIR"
  echo "Index: $OUTPUT_DIR/INDEX.md"
}

main "$@"
