name: Documentation task
description: Improve repository documentation
title: "docs: "
labels:
  - documentation
body:
  - type: textarea
    id: documentation-change
    attributes:
      label: Documentation change
      description: What should be added or improved?
    validations:
      required: true
